import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import type { SprayJob } from "./types";

function esc(v: unknown): string {
  if (v == null || v === "") return "—";
  return String(v).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function weatherLine(j: SprayJob): string {
  const parts: string[] = [];
  if (j.temperature_c != null) parts.push(`${j.temperature_c}°C`);
  if (j.humidity != null) parts.push(`${j.humidity}% RH`);
  if (j.delta_t != null) parts.push(`ΔT ${j.delta_t}`);
  if (j.wind_speed != null) parts.push(`wind ${j.wind_speed} km/h${j.wind_direction ? ` ${j.wind_direction}` : ""}`);
  return parts.length ? parts.join(" · ") : "—";
}

function jobRowHtml(j: SprayJob): string {
  const products = j.products.length
    ? j.products.map((p) => {
        const total = p.total_qty != null ? ` (total ${p.total_qty.toFixed(2)} ${p.total_qty_unit ?? ""})` : "";
        return `${esc(p.chemical_name)} @ ${esc(p.rate)} ${esc(p.unit)}${total}`;
      }).join("<br/>")
    : "—";
  return `
    <tr>
      <td>${esc(j.date)}</td>
      <td>${esc(j.farm_name)}<br/><span class="muted">${esc(j.paddock_name)}</span></td>
      <td>${esc(j.crop)}${j.variety ? ` (${esc(j.variety)})` : ""}</td>
      <td>${esc(j.target)}</td>
      <td>${products}</td>
      <td>${j.area_ha ?? j.actual_area_ha ?? "—"} ha</td>
      <td>${esc(j.operator)}<br/><span class="muted">${esc(j.machinery_name)}</span></td>
      <td>${weatherLine(j)}</td>
    </tr>`;
}

function reportHtml(jobs: SprayJob[], businessName: string): string {
  const generated = new Date().toLocaleString();
  const range = jobs.length
    ? `${[...jobs].sort((a, b) => (a.date < b.date ? -1 : 1))[0].date} – ${[...jobs].sort((a, b) => (a.date < b.date ? 1 : -1))[0].date}`
    : "—";
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1A1A1A; padding: 24px; }
  h1 { font-size: 20px; margin: 0 0 2px; }
  .meta { color: #666; font-size: 11px; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th { text-align: left; background: #0F5132; color: #fff; padding: 6px 8px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.3px; }
  td { padding: 6px 8px; border-bottom: 1px solid #E5E5E5; vertical-align: top; }
  tr:nth-child(even) td { background: #F7F7F5; }
  .muted { color: #888; font-size: 9px; }
  .footer { margin-top: 16px; font-size: 9px; color: #999; }
</style>
</head>
<body>
  <h1>${esc(businessName)} — Spray Application Record</h1>
  <div class="meta">${jobs.length} record${jobs.length === 1 ? "" : "s"} · ${esc(range)} · generated ${esc(generated)}</div>
  <table>
    <thead>
      <tr>
        <th>Date</th><th>Farm / Paddock</th><th>Crop</th><th>Target</th>
        <th>Product(s)</th><th>Area</th><th>Operator / Machine</th><th>Weather at application</th>
      </tr>
    </thead>
    <tbody>
      ${jobs.map(jobRowHtml).join("\n")}
    </tbody>
  </table>
  <div class="footer">Generated by Chaser. Weather figures are as captured on-device at the start of each job.</div>
</body>
</html>`;
}

export async function exportJobsPdf(jobs: SprayJob[], businessName: string): Promise<{ ok: boolean; message?: string }> {
  const html = reportHtml(jobs, businessName);

  if (Platform.OS === "web") {
    try {
      await Print.printAsync({ html });
      return { ok: true };
    } catch (e: any) {
      return { ok: false, message: e?.message ?? "Print failed" };
    }
  }

  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Export Spray Records (PDF)" });
      return { ok: true };
    }
    return { ok: true, message: `Saved to ${uri}` };
  } catch (e: any) {
    return { ok: false, message: e?.message ?? "Export failed" };
  }
}
